[package]
name = "yew-app"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
yew = "0.18"
web-sys = "0.3.55"
log = "0.4"
wasm-logger = "0.2"
