name = "yewlife"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./dist",entry-point = "workers-site"}
compatibility_date = "2021-09-24"
